services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: docker-gui-server
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - PORT=3001
      - HOST=0.0.0.0
      - DOCKER_SOCKET_PATH=/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: docker-gui-web
    environment:
      - VITE_API_URL=/api
    depends_on:
      server:
        condition: service_healthy
    ports:
      - "8080:80"
    restart: unless-stopped

networks:
  default:
    name: docker-gui
