services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: docker-gui-server
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - PORT=3001
      - HOST=0.0.0.0
      - DOCKER_SOCKET_PATH=/var/run/docker.sock
      - SAFE_MODE=${SAFE_MODE:-false}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-200}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-1 minute}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-}
    user: "100:984"  # app user with docker group
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://0.0.0.0:3001/api/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: docker-gui-web
    environment:
      - VITE_API_URL=/api
    depends_on:
      server:
        condition: service_healthy
    ports:
      - "8086:80"
    restart: unless-stopped

networks:
  default:
    name: docker-gui
